# Generated by Django 6.0 on 2025-12-29 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='Name of the book', max_length=50)),
                ('URL', models.URLField(blank=True, default='www.bookurl.com')),
                ('Plain_contents', models.TextField(blank=True, default='')),
                ('Embedded_contents', models.TextField(blank='', default='')),
                ('Uploaded_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_query', models.CharField(max_length=100)),
                ('AI_response', models.TextField()),
                ('PDF', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai.pdfmodel')),
            ],
        ),
    ]
