# Generated by Django 6.0 on 2025-12-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfmodel',
            name='Uploaded_by',
        ),
    ]
