# Generated by Django 6.0 on 2025-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodel',
            name='Contents',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pdfmodel',
            name='Title',
            field=models.CharField(blank=True, default='Name of the book', max_length=50),
        ),
        migrations.AlterField(
            model_name='pdfmodel',
            name='URL',
            field=models.URLField(blank=True, default='www.bookurl.com'),
        ),
    ]
