# Generated by Django 6.0 on 2025-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_pdfmodel_contents_alter_pdfmodel_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfmodel',
            old_name='Contents',
            new_name='Plain_contents',
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='Embedded_contents',
            field=models.TextField(blank='', default=''),
        ),
    ]
