# Generated by Django 6.0 on 2025-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_pdfmodel_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='Embedded_contents',
            field=models.JSONField(blank='', default=''),
        ),
    ]
