# Generated by Django 6.0 on 2025-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_rename_contents_pdfmodel_plain_contents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_query', models.CharField(max_length=100)),
                ('AI_response', models.TextField()),
            ],
        ),
    ]
