# Generated by Django 6.0 on 2025-12-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_pdfmodel_embedded_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Embedded_contents', models.JSONField(blank='', default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdfmodel',
            name='Embedded_contents',
        ),
    ]
