# Generated by Django 6.0 on 2025-12-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_embeddedpdf_remove_pdfmodel_embedded_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedpdf',
            name='Embedded_contents',
            field=models.TextField(blank='', default=''),
        ),
    ]
